### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Egozjuer** [tusen-ai/EchoFusion#1]
Hello,When I deal with k-radar dataset,it didn't work well,

`Traceback (most recent call last):
  File "datasets/kradar_detection_v1_0.py", line 1001, in <module>
    dataset.generate_sparse_rdr_cube()
  File "datasets/kradar_detection_v1_0.py", line 802, in generate_sparse_rdr_cube
    sparse_rdr_cube = self.get_sparse_rdr_cube_from_rdr_cube(dict_item)
  File "datasets/kradar_detection_v1_0.py", line 721, in get_sparse_rdr_cube_from_rdr_cube
    rdr_cube = torch.from_numpy(dict_item['rdr_cube'])
TypeError: 'NoneType' object is not subscriptable`
Please tell me how to solve the problem

**Comment by Egozjuer** [comment]
the command is python datasets/kradar_detection_v1_0.py
 10%|█████████▍                                                                                        | 595/6196 [07:35<1:27:51,  1.06it/s]* Exception error (Dataset): __getitem__ error
 10%|█████████▍                                                                                        | 595/6196 [07:35<1:11:25,  1.31it/s]

**Comment by Egozjuer** [comment]
@DekuLiuTesla ,Hi

**Comment by kjnyeong** [comment]
The RADIal dataset Google Drive link is invalid.
